In [1]:
%matplotlib
import pandas as pd
import numpy as np

Using matplotlib backend: Qt4Agg

In [2]:
potholes  =pd.read_csv('Potholes_Patched.csv')

In [3]:
potholes.columns

Index(['﻿CREATION DATE', 'STATUS', 'COMPLETION DATE', 'SERVICE REQUEST NUMBER',
       'TYPE OF SERVICE REQUEST', 'CURRENT ACTIVITY', 'MOST RECENT ACTION',
       'NUMBER OF POTHOLES FILLED ON BLOCK', 'STREET ADDRESS', 'ZIP',
       'X COORDINATE', 'Y COORDINATE', 'Ward', 'Police District',
       'Community Area', 'LATITUDE', 'LONGITUDE', 'LOCATION'],
      dtype='object')

In [4]:
melt = pd.melt(potholes, id_vars='STATUS')

In [5]:
melt.iloc[0:5, :]

      STATUS        variable       value
0  Completed  ﻿CREATION DATE  05/01/2017
1  Completed  ﻿CREATION DATE  04/27/2017
2  Completed  ﻿CREATION DATE  04/26/2017
3  Completed  ﻿CREATION DATE  04/26/2017
4  Completed  ﻿CREATION DATE  04/25/2017

In [6]:
melt = pd.melt(potholes, id_vars='ZIP')

In [7]:
melt.iloc[0:5, :]

     ZIP        variable       value
0  60642  ﻿CREATION DATE  05/01/2017
1  60612  ﻿CREATION DATE  04/27/2017
2  60610  ﻿CREATION DATE  04/26/2017
3  60607  ﻿CREATION DATE  04/26/2017
4  60642  ﻿CREATION DATE  04/25/2017

In [8]:
potholes.describe()

,NUMBER OF POTHOLES FILLED ON BLOCK,ZIP,X COORDINATE,Y COORDINATE,Ward,Police District,Community Area,LATITUDE,LONGITUDE
count,40.000000,40.000000,4.000000e+01,4.000000e+01,40.000000,40.000000,40.000000,40.000000,40.000000
mean,11.650000,60620.450000,1.162390e+06,1.902942e+06,25.800000,12.375000,24.950000,41.889386,-87.679251
std,14.130436,14.507204,6.111527e+03,4.376646e+03,6.169403,2.349986,4.477579,0.012081,0.022419
min,1.000000,60607.000000,1.153826e+06,1.895655e+06,1.000000,1.000000,8.000000,41.869371,-87.711021
25%,3.000000,60612.000000,1.157479e+06,1.898743e+06,26.000000,12.000000,24.000000,41.877815,-87.697323
50%,6.500000,60612.000000,1.162469e+06,1.902627e+06,27.000000,12.000000,25.500000,41.888501,-87.679252
75%,15.000000,60622.000000,1.166134e+06,1.905939e+06,27.000000,12.000000,28.000000,41.897684,-87.665553
max,63.000000,60651.000000,1.179091e+06,1.910450e+06,42.000000,18.000000,28.000000,41.909986,-87.617560

In [9]:
pd.crosstab(potholes['Ward'], potholes['STATUS'])

STATUS  Completed
Ward
1               1
2               1
25              1
26             11
27             24
28              1
42              1

In [10]:
potholes= potholes[(potholes['STATUS']=='Completed')&(potholes['Ward']==27)]

In [11]:
potholes

,﻿CREATION DATE,STATUS,COMPLETION DATE,SERVICE REQUEST NUMBER,TYPE OF SERVICE REQUEST,CURRENT ACTIVITY,MOST RECENT ACTION,NUMBER OF POTHOLES FILLED ON BLOCK,STREET ADDRESS,ZIP,X COORDINATE,Y COORDINATE,Ward,Police District,Community Area,LATITUDE,LONGITUDE,LOCATION
0,05/01/2017,Completed,05/01/2017,17-02676457,Pothole in Street,Final Outcome,Pothole Patched,15,800 N SANGAMON ST,60642,1.169789e+06,1.905547e+06,27,12,24,41.896373,-87.651991,"(41.89637340908142, -87.65199056194821)"
1,04/27/2017,Completed,05/01/2017,17-02563630,Pothole in Street,Final Outcome,Pothole Patched,15,2000 W POLK ST,60612,1.163272e+06,1.896444e+06,27,12,28,41.871593,-87.676054,"(41.871592594832485, -87.67605358490512)"
2,04/26/2017,Completed,05/01/2017,17-02530242,Pothole in Street,Final Outcome,Pothole Patched,63,800 N SEDGWICK ST,60610,1.173387e+06,1.905652e+06,27,18,8,41.896633,-87.638794,"(41.896632588512325, -87.63879390432517)"
3,04/26/2017,Completed,05/01/2017,17-02532659,Pothole in Street,Final Outcome,Pothole Patched,19,174 N RACINE AVE,60607,1.168478e+06,1.901396e+06,27,12,28,41.885214,-87.656934,"(41.88521446621154, -87.65693439365975)"
4,04/25/2017,Completed,05/01/2017,17-02498592,Pothole in Street,Final Outcome,Pothole Patched,5,808 N LESSING ST,60642,1.170063e+06,1.905681e+06,27,12,24,41.896715,-87.650974,"(41.8967151021304, -87.65097364881396)"
5,04/25/2017,Completed,05/01/2017,17-02511204,Pothole in Street,Final Outcome,Pothole Patched,33,955 W GRAND AVE,60642,1.169905e+06,1.903659e+06,27,12,24,41.891026,-87.652005,"(41.89102614763669, -87.65200458816506)"
6,04/25/2017,Completed,05/01/2017,17-02512252,Pothole in Street,Final Outcome,Pothole Patched,3,1320 W JACKSON BLVD,60607,1.167636e+06,1.898759e+06,27,12,28,41.877847,-87.660332,"(41.87784659640014, -87.66033207552151)"
7,04/24/2017,Completed,05/01/2017,17-02463809,Pothole in Street,Final Outcome,Pothole Patched,12,1826 W OGDEN AVE,60612,1.164293e+06,1.898195e+06,27,12,28,41.876320,-87.672370,"(41.87631974213966, -87.67236952668931)"
8,04/18/2017,Completed,05/01/2017,17-02295497,Pothole in Street,Final Outcome,Pothole Patched,3,1622 W JACKSON BLVD,60612,1.165648e+06,1.898697e+06,27,12,28,41.877719,-87.667672,"(41.87771858713392, -87.66767161604247)"
9,04/18/2017,Completed,05/01/2017,17-02295549,Pothole in Street,Final Outcome,Pothole Patched,1,1638 W VAN BUREN ST,60612,1.165425e+06,1.898228e+06,27,12,28,41.876438,-87.668314,"(41.87643831031682, -87.66831380480193)"
10,04/18/2017,Completed,05/01/2017,17-02307895,Pothole in Street,Final Outcome,Pothole Patched,25,1600 W TAYLOR ST,60612,1.165885e+06,1.895655e+06,27,12,28,41.869371,-87.666529,"(41.869371084501246, -87.66652853002904)"
22,05/04/2017,Completed,05/04/2017,17-02754996,Pothole in Street,Final Outcome,Pothole Patched,4,700 S DAMEN AVE,60612,1.163163e+06,1.896907e+06,27,12,28,41.872691,-87.676565,"(41.87269118179103, -87.67656541644642)"
23,05/02/2017,Completed,05/04/2017,17-02698235,Pothole in Street,Final Outcome,Pothole Patched,20,2925 W CARROLL AVE,60612,1.156824e+06,1.902270e+06,27,12,27,41.887489,-87.699965,"(41.88748888426041, -87.69996469480603)"
24,05/02/2017,Completed,05/04/2017,17-02699321,Pothole in Street,Final Outcome,Pothole Patched,18,19 N LOOMIS ST,60607,1.166988e+06,1.900226e+06,27,12,28,41.882130,-87.662144,"(41.882130390346205, -87.66214445315201)"
25,05/02/2017,Completed,05/04/2017,17-02702374,Pothole in Street,Final Outcome,Pothole Patched,6,820 S DAMEN AVE,60612,1.163179e+06,1.896347e+06,27,12,28,41.870889,-87.676513,"(41.87088949605217, -87.67651265022583)"
28,04/29/2017,Completed,05/04/2017,17-02629765,Pothole in Street,Final Outcome,Pothole Patched,4,442 N SACRAMENTO BLVD,60612,1.156287e+06,1.902983e+06,27,12,23,41.889512,-87.701620,"(41.889512287432765, -87.70161975736556)"
29,04/28/2017,Completed,05/04/2017,17-02585558,Pothole in Street,Final Outcome,Pothole Patched,2,216 N OGDEN AVE,60607,1.166879e+06,1.901572e+06,27,12,28,41.885807,-87.662626,"(41.885807322053225, -87.66262609659275)"
30,04/28/2017,Completed,05/04/2017,17-02590298,Pothole in Street,Final Outcome,Pothole Patched,11,3000 W CHICAGO AVE,60622,1.156080e+06,1.905177e+06,27,12,23,41.895705,-87.702219,"(41.895704524946225, -87.70221852353758)"
31,04/28/2017,Completed,05/04/2017,17-02596586,Pothole in Street,Final Outcome,Pothole Patched,12,34 N SACRAMENTO BLVD,60612,1.156381e+06,1.900203e+06,27,12,27,41.881984,-87.701379,"(41.88198420214532, -87.70137922487692)"
32,04/27/2017,Completed,05/04/2017,17-02564818,Pothole in Street,Final Outcome,Pothole Patched,19,1935 W HARRISON ST,60612,1.163511e+06,1.897386e+06,27,12,28,41.873958,-87.674813,"(41.87395788089127, -87.67481325263503)"
33,04/24/2017,Completed,05/04/2017,17-02482018,Pothole in Street,Final Outcome,Pothole Patched,63,200 N ASHLAND AVE,60607,1.165704e+06,1.901508e+06,27,12,28,41.885349,-87.667114,"(41.885348558810065, -87.66711440377276)"
34,04/24/2017,Completed,05/04/2017,17-02489744,Pothole in Street,Final Outcome,Pothole Patched,15,2800 W LAKE ST,60612,1.157697e+06,1.901052e+06,27,12,27,41.884351,-87.696443,"(41.88435147833913, -87.6964425612067)"
35,04/24/2017,Completed,05/04/2017,17-02489747,Pothole in Street,Final Outcome,Pothole Patched,7,2600 W LAKE ST,60612,1.159038e+06,1.901132e+06,27,12,28,41.884542,-87.691527,"(41.88454189242629, -87.69152708911913)"
36,04/24/2017,Completed,05/04/2017,17-02489755,Pothole in Street,Final Outcome,Pothole Patched,11,2400 W LAKE ST,60612,1.160377e+06,1.901215e+06,27,12,28,41.884743,-87.686595,"(41.88474313602135, -87.68659460616315)"

In [12]:
potholes.shape

(24, 18)

In [13]:
qry1 = potholes.query('(Ward > 10 )').head()

In [14]:
qry1.shape

(5, 18)

In [15]:
groupedData = potholes.groupby(['ZIP', 'Ward']).mean()

In [16]:
groupedData

,,NUMBER OF POTHOLES FILLED ON BLOCK,X COORDINATE,Y COORDINATE,Police District,Community Area,LATITUDE,LONGITUDE
ZIP,Ward,,,,,,,
60607,27,21.000000,1.167137e+06,1.900692e+06,12.0,28.000000,41.883269,-87.661830
60610,27,63.000000,1.173387e+06,1.905652e+06,18.0,8.000000,41.896633,-87.638794
60612,27,11.000000,1.161499e+06,1.899051e+06,12.0,27.428571,41.878686,-87.682597
60622,27,11.000000,1.156080e+06,1.905177e+06,12.0,23.000000,41.895705,-87.702219
60642,27,17.666667,1.169919e+06,1.904963e+06,12.0,24.000000,41.894705,-87.651656

In [17]:
groupedData.shape

(5, 7)

In [19]:
grouped1 = groupedData['NUMBER OF POTHOLES FILLED ON BLOCK'].unique()
grouped1

array([ 21.        ,  63.        ,  11.        ,  17.66666667])

In [20]:
grouped1.shape

(4,)

In [22]:
(potholes.ix[:, 'ZIP'] == 60642).any()

True

In [23]:
potholes.ZIP.describe()

count       24.000000
mean     60615.041667
std         10.848679
min      60607.000000
25%      60611.500000
50%      60612.000000
75%      60612.000000
max      60642.000000
Name: ZIP, dtype: float64

In [24]:
potholes.groupby('ZIP').aggregate(np.mean)

,NUMBER OF POTHOLES FILLED ON BLOCK,X COORDINATE,Y COORDINATE,Ward,Police District,Community Area,LATITUDE,LONGITUDE
ZIP,,,,,,,,
60607,21.000000,1.167137e+06,1.900692e+06,27.0,12.0,28.000000,41.883269,-87.661830
60610,63.000000,1.173387e+06,1.905652e+06,27.0,18.0,8.000000,41.896633,-87.638794
60612,11.000000,1.161499e+06,1.899051e+06,27.0,12.0,27.428571,41.878686,-87.682597
60622,11.000000,1.156080e+06,1.905177e+06,27.0,12.0,23.000000,41.895705,-87.702219
60642,17.666667,1.169919e+06,1.904963e+06,27.0,12.0,24.000000,41.894705,-87.651656

In [25]:
potholes.groupby('ZIP').aggregate(np.sum)

,NUMBER OF POTHOLES FILLED ON BLOCK,X COORDINATE,Y COORDINATE,Ward,Police District,Community Area,LATITUDE,LONGITUDE
ZIP,,,,,,,,
60607,105,5.835685e+06,9.503462e+06,135,60,140,209.416347,-438.309151
60610,63,1.173387e+06,1.905652e+06,27,18,8,41.896633,-87.638794
60612,154,1.626098e+07,2.658671e+07,378,168,384,586.301601,-1227.556356
60622,11,1.156080e+06,1.905177e+06,27,12,23,41.895705,-87.702219
60642,53,3.509757e+06,5.714888e+06,81,36,72,125.684115,-262.954969

In [28]:
criteria = potholes['STATUS'].map(lambda x: x.startswith('C'))

In [29]:
criteria.head()

0    True
1    True
2    True
3    True
4    True
Name: STATUS, dtype: bool